config/routes.rb
David::Application.routes.draw do
	resources :blogs
  get "main/index"
	get "/portfolio", to: 'main#portfolio', as: :portfolio
	get "/about", to: 'main#about', as: :about
  devise_for :admins
	# root to: 'blogs#index'
	root to: 'main#portfolio'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	validates_presence_of :title, :body
	has_attached_file :pic, {
		:styles => {:thumb =>["112x112#", :jpg]},
		:convert_options => {
			:medium => "-quality 80 -interlace Plane",
			:thumb => "-quality 80 -interlace Plane"
		}, :processors => [:thumbnail, :compression],
			:default_url => "missing.png"
	} 

	def time
		created_at.strftime("%b. %e, %Y")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_filter :authenticate_admin!, only: [:new, :create, :edit, :update]

	def show
		@blog = Blog.find(params[:id])
	end

	def index
		@blogs = Blog.all
	end

	def new
		@blog = Blog.new
	end

	def create
		@blog = Blog.new(blog_params)

		if @blog.save
			redirect_to @blog
			flash[:notice] = "#{@blog.title} successfully created"
		else
			render :new
			# msg = @blog.errors.full_messages.collect.join(' ')
			# flash[:error] = "#{msg}"
			flash[:error] = "Error"
		end
	end

	def edit
		@blog = Blog.find(params[:id])
	end

	def update
		@blog = Blog.find(params[:id])

		if @blog.update_attributes(blog_params)
			redirect_to @blog
			flash[:notice] = "#{@blog.title} successfully updated"
		else
			redirect_to edit_blog_path(@blog)	
			flash[:error] = "Error updating blog"
		end
	end

	def destroy
		@blog = Blog.find(params[:id])
		@blog.destroy
		redirect_to blogs_path
	end

	private
		def blog_params
			params.require(:blog).permit(:title, :body, :pic)
		end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

	def portfolio
	end

	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class CodeRayify < Redcarpet::Render::HTML
		def block_code(code, language)
			CodeRay.scan(code, language).div
		end
	end

	def markdown(text)
		coderayified = CodeRayify.new(:filter_html => true, 
																	:hard_wrap => true)
		options = {
			:fenced_code_blocks => true,
			:no_intra_emphasis => true,
			:autolink => true,
			:strikethrough => true,
			:lax_html_blocks => true,
			:superscript => true
		}
		markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
		markdown_to_html.render(text).html_safe
	end
end

app/views/blogs/_form.html.erb
<div class="blog_form_wrapper">
	<%= simple_form_for @blog do |f| %>
		<%= f.input :title %>
		<%= f.input :body %>
		<%= f.input :pic %>
		<%= f.button :submit %>
	<% end %>
</div>

app/views/blogs/edit.html.erb
<%= render 'form' %>

app/views/blogs/index.html.erb
<div class="blog_wrapper">
	<% @blogs.each do |blog| %>
		<div class="row">
			<div class="large-2 columns pic_and_time">
				<%= image_tag blog.pic.url(:thumb) %>
				<div class="time"><%= blog.time %></div>
			</div>

			<div class="large-10 columns blog">
				<h3><%= link_to blog.title, blog %></h3>
			</div>
		</div>

		<div class="large-10 columns large-centered body">
			<%= markdown blog.body %>
		</div>
		<hr />
	<% end %>
</div>

app/views/blogs/new.html.erb
<%= render "form" %>

app/views/blogs/show.html.erb
<div class="blog_wrapper">
	<div class="large-2 columns pic_and_time">
		<%= image_tag @blog.pic.url(:thumb) %>
		<div class="time"><%= @blog.time %></div>
	</div>

	<div class="large-10 columns blog">
		<h3><%= link_to @blog.title, @blog %></h3>
	</div>

	<div class="large-10 columns large-centered body">
		<%= markdown @blog.body %>
	</div>
	<hr />
<div>

<% if admin_signed_in? %>
	<%= link_to 'Edit', edit_blog_path(@blog), class: 'button' %>
	<%= link_to 'Destroy', blog_path, method: :delete, class: 'button' %>
<% end %>

app/views/layouts/_admin_nav.html.erb
<div class="admin_nav_wrapper">
	<%= link_to 'New Blog', new_blog_path %>
	<%= link_to 'Sign out', destroy_admin_session_path, method: :delete %>
</div>

app/views/layouts/_flash.html.erb
<div class="flash_wrapper">
	<% if flash[:notice] %>
		<div class="alert-box success"><%= flash[:notice] %></div>
	<% elsif flash[:alert] %>
		<div class="alert-box"><%= flash[:alert] %></div>
	<% elsif flash[:error] %>
		<div class="alert-box alert"><%= flash[:error] %></div>
	<% end %>
</div>

app/views/layouts/_ga.html.erb
<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-46461811-1', 'davidbegin.com');
	ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<div class="header_wrapper row">
	<div class="large-9 medium-7 small-6 columns">
		<div class="header">
			<%= link_to 'David Begin', root_path, class: 'header_link' %> 
			<ul class="menu">
				<li><%# link_to 'Blog', root_path %></li>
				<li><%= link_to 'Portfolio', portfolio_path %></li>
				<li><%= link_to 'About', about_path %></li>
				<li class="github"><%= link_to 'Github',  'https://github.com/presidentJFK' %></li>
				<li class="email"><%= link_to 'Email', 'mailto:davidmichaelbe@gmail.com?subject=Hello David!' %></li>
			</ul>
		</div>
	</div>

	<div class="bars_wrapper">
		<%= fa_icon 'bars' %>
	</div>

	<div class="large-3 medium-4 small-6 columns icons">
		<%= link_to 'https://github.com/presidentJFK', class: 'github' do %>
			<%= fa_icon "github" %>
		<% end %>
		<%= link_to "mailto:davidmichaelbe@gmail.com?subject=Hello David!" do %>
			<%= fa_icon "envelope-o" %>
		<% end %>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<title><%= content_for?(:title) ? yield(:title) : "David Begin" %></title>

		<%= stylesheet_link_tag    "application" %>
		<%= javascript_include_tag "vendor/modernizr" %>
		<%= csrf_meta_tags %>
		<%= favicon_link_tag %>
	</head>

	<body class="row" id="body">

		<div class="large-11 columns large-centered">
			<%= render 'layouts/header' %>
			<%= render 'layouts/flash' %>

			<% if admin_signed_in? %>
				<%= render 'layouts/admin_nav' %>
			<% end %>

			<%= yield %>
		</div>
		
		<%= render 'layouts/ga' %>
		<%= javascript_include_tag "application" %>
	</body>
</html>

app/views/main/about.html.erb
<div class="large-12 columns about">
	My name is David Begin, and I 25 year old Rubyist living in Portland, Oregon.
	I currently freelance, making Web Applications using mostly Ruby on Rails. I am passionate about 
	programming and technology, and love learning new things, whether that be wading through man pages or a spirited discuss
	with fellow programmers.
</div>

app/views/main/index.html.erb
<div class="tag">
	Just a young programmer following his dreams in PDX.
</div>

app/views/main/portfolio.html.erb
<div class="large-6 columns portfolio_wrapper">
	<div class="website"> 
		<div class="header">Aalto Photography</div>	

		<div class="description">
			Personal Site of Photographer Patrick Aalto.<br />
			<%= link_to 'http://www.aaltophotography.com/', 'http://www.aaltophotography.com/' %>
		</div>
	</div>

	<div class="website"> 
		<div class="header">Rhythm and Strings Music Therapy</div>	

		<div class="description">
			Website and Blog for Portland based Music Therapist Mariee Durfee.<br />
			<%= link_to 'http://www.rhythmandstrings.com/', 'http://www.rhythmandstrings.com/' %>
		</div>
	</div>


	<div class="website"> 
		<div class="header">Impact Performance Training</div>	

		<div class="description">
			Website for Newburg based Gym and Training facility.<br />
			<%= link_to 'http://impactperformancetraining.net/', 'http://impactperformancetraining.net/' %>
		</div>
	</div>

	<div class="website"> 
		<div class="header">Dewey Nielsen</div>	

		<div class="description">
			Personal Website of Physical Trainer Dewey Nielsen.<br />
			<%= link_to 'http://deweynielsen.com/', 'http://deweynielsen.com/' %>
		</div>
	</div>

	<div class="website"> 
		<div class="header">Fitment Garage</div>	

		<div class="description">
			Australia Car Parts company.<br />
			<%= link_to 'http://www.fitmentgarage.com/', 'http://www.fitmentgarage.com/' %>
		</div>
	</div>

	<div class="website"> 
		<div class="header">Backscratch</div>	

		<div class="description">
			A simple todo app built with Backbone.js<br />
			<%= link_to 'http://backscratch.herokuapp.com/', 'http://backscratch.herokuapp.com/' %>
		</div>
	</div>
</div>

<div class="large-6 columns">
	<div class="images">
		<ul class="clearing-thumbs" data-clearing>
			<li><%= link_to image_tag('dewey-thumb.jpg'), '/assets/dewey.jpg' %></li>
			<li><%= link_to image_tag('impact-about-thumb.jpg'), '/assets/impact-about.jpg' %></li>
			<li><%= link_to image_tag('marie-home-thumb.jpg'), '/assets/marie-home.jpg' %></li>
			<li><%= link_to image_tag('marie-service-thumb.jpg'), '/assets/marie-service.jpg' %></li>
			<li><%= link_to image_tag('membership-thumb.jpg'), '/assets/membership.jpg' %></li>
			<li><%= link_to image_tag('patrick-blog-thumb.jpg'), '/assets/patrick-blog.jpg' %></li>
			<li><%= link_to image_tag('patrick-home-thumb.jpg'), '/assets/patrick-home.jpg' %></li>
			<li><%= link_to image_tag('dewey-post-thumb.jpg'), '/assets/dewey-post.jpg' %></li>
			<li><%= link_to image_tag('patrick-weddings-thumb.jpg'), '/assets/patrick-weddings.jpg' %></li>
			<li><%= link_to image_tag('patrick-photos-thumb.jpg'), '/assets/patrick-photos.jpg' %></li>
		</ul>	
	</div>
</div>